//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixel3D.P2P {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserVisibleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserVisibleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixel3D.Network.P2P.UserVisibleStrings", typeof(UserVisibleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected by server.
        /// </summary>
        internal static string DisconnectedByServer {
            get {
                return ResourceManager.GetString("DisconnectedByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected by server (unknown reason).
        /// </summary>
        internal static string DisconnectedByServerUnknownReason {
            get {
                return ResourceManager.GetString("DisconnectedByServerUnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from server (no host migration target).
        /// </summary>
        internal static string DisconnectedFromServerNoHostMigrationTarget {
            get {
                return ResourceManager.GetString("DisconnectedFromServerNoHostMigrationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in data from server.
        /// </summary>
        internal static string ErrorInDataFromServer {
            get {
                return ResourceManager.GetString("ErrorInDataFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is full.
        /// </summary>
        internal static string GameIsFull {
            get {
                return ResourceManager.GetString("GameIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game version mismatch.
        /// </summary>
        internal static string GameVersionMismatch {
            get {
                return ResourceManager.GetString("GameVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host migration timed out.
        /// </summary>
        internal static string HostMigrationTimedOut {
            get {
                return ResourceManager.GetString("HostMigrationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server rejected connection.
        /// </summary>
        internal static string ServerRejectedConnection {
            get {
                return ResourceManager.GetString("ServerRejectedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server shutting down.
        /// </summary>
        internal static string ServerShuttingDown {
            get {
                return ResourceManager.GetString("ServerShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server timed out.
        /// </summary>
        internal static string ServerTimedOut {
            get {
                return ResourceManager.GetString("ServerTimedOut", resourceCulture);
            }
        }
    }
}
